package com.frenchfriesfamily.whowantstobeamillionaire.view.main

import com.frenchfriesfamily.whowantstobeamillionaire.R
import com.frenchfriesfamily.whowantstobeamillionaire.databinding.ActivityMainBinding
import com.frenchfriesfamily.whowantstobeamillionaire.view.base.BaseActivity

class MainActivity : BaseActivity<ActivityMainBinding>(R.layout.activity_main)